### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by wmarchewka** [etdds/esp-idf-lvgl-displays#1]
Thanks for the library !

You have a type in the documentation, for Direct Component and Submodule Component instructions

![Screenshot 2023-03-24 at 9 23 29 AM](https://user-images.githubusercontent.com/5186401/227533198-31ecccae-e122-46b7-b7da-42e85b8a85e9.png)

**Comment by etdds** [comment]
Nice catch. Thanks @wmarchewka. Updated the readme accordingly.
